package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/daichitsuchiya/food-delivery-tracker/internal/infrastructure/graphql/generated"
	orderapp "github.com/daichitsuchiya/food-delivery-tracker/internal/order/application"
	restaurantapp "github.com/daichitsuchiya/food-delivery-tracker/internal/restaurant/application"
	"github.com/daichitsuchiya/food-delivery-tracker/internal/shared/fp"
	"github.com/daichitsuchiya/food-delivery-tracker/internal/shared/types"
)

// PlaceOrder is the resolver for the placeOrder field.
func (r *mutationResolver) PlaceOrder(ctx context.Context, input generated.PlaceOrderInput) (*generated.Order, error) {
	customerID, err := types.ParseCustomerID(input.CustomerID)
	if err != nil {
		return nil, fmt.Errorf("invalid customer ID: %w", err)
	}
	restaurantID, err := types.ParseRestaurantID(input.RestaurantID)
	if err != nil {
		return nil, fmt.Errorf("invalid restaurant ID: %w", err)
	}

	items := fp.Map(input.Items, func(i *generated.PlaceOrderItemInput) orderapp.PlaceOrderItem {
		menuItemID, _ := types.ParseOrderID(i.MenuItemID)
		instructions := ""
		if i.SpecialInstructions != nil {
			instructions = *i.SpecialInstructions
		}
		return orderapp.PlaceOrderItem{
			MenuItemID:          types.MenuItemIDFrom(menuItemID.UUID()),
			Name:                i.Name,
			Quantity:            i.Quantity,
			UnitPrice:           types.JPY(int64(i.UnitPrice)),
			SpecialInstructions: instructions,
		}
	})

	order, err := r.OrderService.PlaceOrder(ctx, orderapp.PlaceOrderCommand{
		CustomerID:   customerID,
		RestaurantID: restaurantID,
		Items:        items,
	})
	if err != nil {
		return nil, err
	}
	return ToGQLOrder(order), nil
}

// ConfirmOrder is the resolver for the confirmOrder field.
func (r *mutationResolver) ConfirmOrder(ctx context.Context, orderID string) (*generated.Order, error) {
	id, err := types.ParseOrderID(orderID)
	if err != nil {
		return nil, fmt.Errorf("invalid order ID: %w", err)
	}
	order, err := r.OrderService.ConfirmOrder(ctx, orderapp.ConfirmOrderCommand{OrderID: id})
	if err != nil {
		return nil, err
	}
	return ToGQLOrder(order), nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, orderID string, reason string) (*generated.Order, error) {
	id, err := types.ParseOrderID(orderID)
	if err != nil {
		return nil, fmt.Errorf("invalid order ID: %w", err)
	}
	order, err := r.OrderService.CancelOrder(ctx, orderapp.CancelOrderCommand{
		OrderID: id,
		Reason:  reason,
	})
	if err != nil {
		return nil, err
	}
	return ToGQLOrder(order), nil
}

// TransitionOrder is the resolver for the transitionOrder field.
func (r *mutationResolver) TransitionOrder(ctx context.Context, orderID string, newStatus generated.OrderStatus) (*generated.Order, error) {
	id, err := types.ParseOrderID(orderID)
	if err != nil {
		return nil, fmt.Errorf("invalid order ID: %w", err)
	}
	order, err := r.OrderService.TransitionOrder(ctx, orderapp.TransitionOrderCommand{
		OrderID:   id,
		NewStatus: string(newStatus),
	})
	if err != nil {
		return nil, err
	}
	return ToGQLOrder(order), nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*generated.Order, error) {
	orderID, err := types.ParseOrderID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid order ID: %w", err)
	}
	order, err := r.OrderService.GetOrder(ctx, orderapp.GetOrderQuery{OrderID: orderID})
	if err != nil {
		return nil, err
	}
	return ToGQLOrder(order), nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, limit *int, offset *int) ([]*generated.Order, error) {
	l, o := 20, 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	orders, err := r.OrderService.ListOrders(ctx, orderapp.ListOrdersQuery{Limit: l, Offset: o})
	if err != nil {
		return nil, err
	}
	return ToGQLOrders(orders), nil
}

// OrdersByStatus is the resolver for the ordersByStatus field.
func (r *queryResolver) OrdersByStatus(ctx context.Context, status generated.OrderStatus) ([]*generated.Order, error) {
	orders, err := r.OrderService.ListOrdersByStatus(ctx, orderapp.ListOrdersByStatusQuery{Status: string(status)})
	if err != nil {
		return nil, err
	}
	return ToGQLOrders(orders), nil
}

// Restaurant is the resolver for the restaurant field.
func (r *queryResolver) Restaurant(ctx context.Context, id string) (*generated.Restaurant, error) {
	restID, err := types.ParseRestaurantID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid restaurant ID: %w", err)
	}
	restaurant, err := r.RestaurantService.GetRestaurant(ctx, restaurantapp.GetRestaurantQuery{RestaurantID: restID})
	if err != nil {
		return nil, err
	}
	return toGQLRestaurant(restaurant), nil
}

// Restaurants is the resolver for the restaurants field.
func (r *queryResolver) Restaurants(ctx context.Context) ([]*generated.Restaurant, error) {
	restaurants, err := r.RestaurantService.ListRestaurants(ctx, restaurantapp.ListRestaurantsQuery{})
	if err != nil {
		return nil, err
	}
	return toGQLRestaurants(restaurants), nil
}

// OrderStatusChanged is the resolver for the orderStatusChanged field.
func (r *subscriptionResolver) OrderStatusChanged(ctx context.Context, orderID string) (<-chan *generated.Order, error) {
	subscriberID := fmt.Sprintf("sub-%s-%d", orderID, time.Now().UnixNano())
	ch, unsubscribe := r.SubscriptionMgr.Subscribe(orderID, subscriberID)

	// Clean up when client disconnects.
	go func() {
		<-ctx.Done()
		unsubscribe()
	}()

	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
